### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by Damianyangyang** [raeslab/omixer-rpm#9]
java -jar omixer-rpm-1.1.jar -a 2 -d /home/bioinfo/sunyy/work/CRC/java_GMMs/omixer-rpm-1.1/GMMs/GMMs.v1.07.txt -i /home/bioinfo/sunyy/work/CRC/java_GMMs/temp/test.tsv -o /home/bioinfo/sunyy/work/CRC/java_GMMs/gmm_output/
Hi，
Theses error occurs when I use the above command. What is the reason?
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.LinkedList.addAll(LinkedList.java:424)
	at java.util.LinkedList.addAll(LinkedList.java:387)
	at java.util.LinkedList.<init>(LinkedList.java:119)
	at org.omixer.rpm.model.Module.makeAllPaths(Module.java:286)
	at org.omixer.rpm.service.impl.ModuleManagerImpl.optimizeModule(ModuleManagerImpl.java:298)
	at org.omixer.rpm.service.impl.ModuleManagerImpl.inferModulesCore(ModuleManagerImpl.java:228)
	at org.omixer.rpm.service.impl.ModuleManagerImpl.inferModules(ModuleManagerImpl.java:106)
	at org.omixer.rpm.service.impl.ModuleManagerImpl.lambda$inferModules$3(ModuleManagerImpl.java:190)
	at org.omixer.rpm.service.impl.ModuleManagerImpl$$Lambda$1/1305193908.accept(Unknown Source)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at org.omixer.rpm.service.impl.ModuleManagerImpl.inferModules(ModuleManagerImpl.java:183)
	at org.omixer.rpm.core.InferenceApp.main(InferenceApp.java:252)

**Comment by omixer** [comment]
Hello,

As written in the error log, Java ran out of memory!

Could you please try running the command as follows?

java -Xmx4G -jar omixer-rpm.jar....

You can increase the amount of given memory if the process still fails!

Please let me know if the above solution doesn't fix your issue!

Best regards,
Youssef

**Comment by Damianyangyang** [comment]
Your solution successfully solved my error! Thanks!
